project:
  type: book

book:
  title: "WLM 2023"
  subtitle: "Конспекты лекций"
  author:
    - name: "Антон Ангельгардт"
      email: "anton.angelgardt@gmail.com"
      affiliations:
        - name: "HSE UX LAB, HSE University"
  date: "3/05/2023"
  chapters:
    - index.qmd
    - part: part-r.qmd
    - part: part-math.qmd
    - part: part-stat.qmd
    - part: part-andan.qmd
    - references.qmd
  favicon: favicon.png
  navbar: 
    title: "WLM 2023 // HSE UX LAB"
    logo: logo.png
    collapse: true
    background: gray-700

bibliography: references.bib

format:
  html:
    cover-image: lec-cover.png
    theme: 
      light: [lightstyle.scss]
      dark: [darkstyle.scss]
  pdf:
    documentclass: scrreprt

editor: visual

