project:
  type: book

book:
  title: "WLM 2023"
  subtitle: "Анализ данных и машинное обучение для исследователей"
  author:
    - name: "Антон Ангельгардт"
      email: "anton.angelgardt@gmail.com"
      affiliations:
        - name: "HSE UX LAB, HSE University"
  date: "3/05/2023"
  chapters:
    - index.qmd
    - part: part-r.qmd
    - rintro.qmd
    - part: part-py.qmd
    - part: part-math.qmd
    - part: part-stat.qmd
    - part: part-andan.qmd
    - part: part-randan.qmd
    - part: part-pyandan.qmd
    - part: part_appendices.qmd
    - appendix_numbers.qmd
    - appendix_strings.qmd
    - appendix_kilobytes.qmd
    - appendix_memory.qmd
    - appendix_proglang.qmd
    - appendix_git.qmd
    - references.qmd
  favicon: pics/favicon.png
  navbar: 
    title: "WLM 2023 // HSE UX LAB"
    logo: pics/logo.png
    collapse: true
    background: gray-700

bibliography: references.bib

format:
  html:
    cover-image: pics/book-cover.png
    theme: 
      light: [lightstyle.scss, chapterlabs.scss, tasklight.scss]
      dark: [darkstyle.scss, chapterlabs.scss, taskdark.scss]
  pdf:
    documentclass: scrreprt

highlight-style: github

editor: visual

